### ISSUE TITLE
Save to file, with the multi API

### ISSUE THREAD

**Issue by gaborcsardi** [jeroen/curl#118]
AFAICT the R multi API does not support this, and it would be awesome. :)

**Comment by gaborcsardi** [comment]
I can also send a PR if you want. Let me know if you have a preferred way for the API. Maybe we could just have a file name parameter in `multi_add`.

**Comment by jeroen** [comment]
Im on vacation now, will look into this next week.

**Comment by jeroen** [comment]
Would you mind elaborating a little bit? Is the use case simply concurrent file downloads? 

In that case perhaps it would be easier to support URL vectors in `curl::download_file` (I think `base::download.file` also supports this).

**Comment by gaborcsardi** [comment]
No, not just parallel downloads, generic async programming.

**Comment by jeroen** [comment]
I've added a `data` callback

**Comment by gaborcsardi** [comment]
Thanks, that should do!

**Comment by jeroen** [comment]
OK great, interested to hear your application.

**Comment by gaborcsardi** [comment]
https://github.com/r-lib/pkgdepends
https://github.com/r-lib/async

**Comment by jeroen** [comment]
You can now also pass a connection object as the `data` argument. This makes writing to files slightly easier:

```r
con <- file("output.txt", open = "wb")
curl::curl_fetch_multi("https://httpbin.org/get", data = con)
curl::multi_run()
close(con)
```

**Comment by gaborcsardi** [comment]
Why not just a file name?

**Comment by gaborcsardi** [comment]
Connections are not great for me, because there is only 128 of them.

**Comment by jeroen** [comment]
I find dealing with file descriptors in C a pain, if possible I would like R to deal with that. Didn't they increase the 128 limit lately?

**Comment by jeroen** [comment]
You can also still pass a function of course as the `data` callback and pass your own write function.

**Comment by gaborcsardi** [comment]
Sure. Calling back to R functions is quite slow, I think the best would be to just handle this within the C code, just like you already handle it in the non-multi case.

I think the function callback is nice, because it is general, I like that. I am just wondering if it is worth to have a simplified and optimized write-to-file shortcut.

**Comment by jeroen** [comment]
I know but this is much more complex. In the non-multi case I can just open the file and close it in the same function when the download is done.

However to do async in C, you'll need to keep track of all the open file descriptors somewhere, and make sure they get closed in all possible scenarios  (request complete, error, failure to start, handle or pool was removed by gc while still open, etc). I very much like the R gc taking care of this :)

**Comment by gaborcsardi** [comment]
How about sticking them into the multi object, and closing them in the finalizer?

**Comment by jeroen** [comment]
They would also need to get closed and removed from the list after requests complete, or error, or fail to start. And then indeed the gc needs to close outstanding fd's when it finalizes the multi pool.

I am not excited about this because the gc is already complex: the multi pool manually protects and releases all handles and callback functions of all pending requests, but those callbacks have other handles and pools in their scope so they get recursively protected, which could lead to a grid lock. I am afraid that adding stuff to manually manage file descriptors into the mix adds more complexity and edge cases.

If you really need it we can look into it. But I think it is more elegant to let R handle files and other connections natively rather than reimplement this in C only to work around the (arbitrary) 128 limit.

**Comment by gaborcsardi** [comment]
OK, thanks!
