### ISSUE TITLE
Inconvenient multi_add API

### ISSUE THREAD

**Issue by hadley** [jeroen/curl#148]
I'm using curl multi to download data from google BigQuery, downloading "pages" of data in parallel. I want to process the json by hand (in C++, for performance), so I want to just save each page to disk in a separate file. To that end, I'm supplying an open connection to `data`. That's a bit painful because if the user accidentally provides a bad combination of parameters, I might have to create 100,000 connections up front - that exhausts all open connections, and makes R + RStudio give weird/uninformative errors. Would it be possible `data` to also take a simple file name, and to open the connection on demand?

**Comment by jeroen** [comment]
> Would it be possible data to also take a simple file name, and to open the connection on demand?

What do you mean by *on demand*? The `data` function gets called many times per download with small chunks of data, usually a few kb. Do you suggest to open and close each file, each time when a chunk of data is received?

The approach I imagine here is that when you create the request, you open the target file and define the `data` callback function. And you can close the file either in the `done` or `fail` callback or after completing `multi_run`. Simple example:

```r
download_async <- function(url, dest = tempfile()){
  con <- file(dest, open = 'wb')
  on.exit(close(con))
  pool <- curl::new_pool()
  total <- 0
  curl::curl_fetch_multi(url, data = function(buf){
    total <<- total + length(buf)
    cat(sprintf("\rDownloaded %d bytes", total))
    writeBin(buf, con)
  }, pool = pool)  
  curl::multi_run(pool = pool)
  dest
}

out <- download_async('https://cran.r-project.org/bin/windows/base/R-3.4.4-win.exe')
``` 

This is indeed restricted by the number of open files in R, but I'm not sure what would be a better solution. However the file should only be open while the connection is active, and you should not be doing 100,000 parallel downloads anyway. Better run them in smaller batches.

**Comment by hadley** [comment]
Why can't `multi_run` just save directly to the file without involving any R connections?

Also it sounds like you're saying that I shouldn't rely on pools to handle very large numbers of downloads, but I should instead set up my own download queue that lots urls to the pool in stages?

**Comment by jeroen** [comment]
I'm not sure how well libcurl handles 100k concurrent downloads, perhaps it's fine. My intuition would be that you get a lot of performance overhead for 100k concurrent downloads. 

Even without involving R connections you may still run into file descriptor limits if you are downloading this many files concurrently. 

If the pages you are downloading fit in memory, an easier solution would be to use the `done` callback rather than the `data` callback. The `done` callback only gets called once per finished download so you can just open a file, write the data, close it.

The `data` callback is just a wrapper around `CURLOPT_WRITEFUNCTION`. It's not doing anything high-level. We could try to add functionality to be smarter, but properly managing open file descriptors in C adds quite a bit of complexity. There are a lot of edge cases where downloads get stalled or interrupted, where you must make sure the C file descriptors get closed nevertheless. The nice thing about the current design is that we can rely on R to open and close the files, and the gc will close them if the user forgets to.

If the main issue with this design is the limit on R connections, it would be easier to implement a connection-like class around file descriptors but without the limitations. Managing open files in C for async downloads is something I would like to avoid, if possible.

**Comment by hadley** [comment]
I thought the pool queued the requests so that only `total_con` were downloaded simultaneously? 

The data does fit in memory, so maybe writing to file once with `done` isn't so bad.

**Comment by jeroen** [comment]
> I thought the pool queued the requests so that only total_con were downloaded simultaneously?

Not necessarily. For example with http2 multiplexing you can have many concurrent downloads over a single http connection, so the actual number of requests could be much larger than `total_con` I think.

> The data does fit in memory, so maybe writing to file once with done isn't so bad.

Yes if you can just write out the data once the download completes in the `done` callback, that makes things much simpler than streaming all these concurrent downloads directly to open files. Also the done callback allows you to detect failed request (e.g. http 404) before you save the data to a file.

**Comment by jeroen** [comment]
If you really want to use the `data` callback, use a pattern like below (similar to what gabor suggests) to open the connection on the first actual write, and then close it when the download is done.

```r
# Lazy-open file on first write
lazyfile <- function(path){
  fd <- NULL
  write_buf <- function(buf){
    if(is.null(fd))
      fd <<- file(path, open = "wb")
    writeBin(buf, fd)
  }
  
  close_fd <- function(...){
    on.exit({fd <<- NULL})
    if(inherits(fd, 'file'))
      base::close(fd)
  }
  #reg.finalizer(environment(), close_fd)
  environment()
}

download_async <- function(url, dest = tempfile()){
  myfile <- lazyfile(dest)
  pool <- curl::new_pool()
  total <- 0
  curl::curl_fetch_multi(url, data = myfile$write_buf, done = myfile$close_fd, pool = pool)  
  curl::multi_run(pool = pool)
  dest
}

out <- download_async('https://cran.r-project.org/bin/windows/base/R-3.4.4-win.exe')
tools::md5sum(out) #a642a3de7b5c2602180e73f4c04b4fbd
```

**Comment by hadley** [comment]
Thanks for the help!

**Comment by jeroen** [comment]
See https://github.com/jeroen/curl/pull/149 for a native implementation.

**Comment by jeroen** [comment]
OK I merged it. You can now pass a file path to the `data` function and it should automatically open and close files when needed. 

Still the `done` callback is probably safer, but if you really want to stream many big files concurrently, this may be useful.
