### ISSUE TITLE
API for custom verify function for SSL

### ISSUE THREAD

**Issue by jimhester** [jeroen/curl#263]
I have a use case where I need to do a custom verification for a TLS certificate. Similar to what they propose in https://curl.se/mail/lib-2016-01/0128.html. I don't believe there is any current support in the curl or openssl R packages for this, but was wondering what you think would be the best API if we were to support this use case?

I would be happy to work on the changes needed once we decide on an interface.

**Comment by jeroen** [comment]
The problem is that this can only work if libcurl is using the openssl TLS back-end. However by default the curl package uses Schannel on Windows and SecureChannel on MacOS. On Linux it depends on if the R bindings were compiled against `libcurl4-openssl-dev` or `libcurl4-gnutls-dev`, or something else. So at best this can work for a select configuration.

If you're OK with that, we would need a binding to [CURLOPT_SSL_CTX_FUNCTION](https://curl.se/libcurl/c/CURLOPT_SSL_CTX_FUNCTION.html) similar as we do [here](https://github.com/jeroen/curl/blob/master/src/handle.c#L286-L316) for some of the other `*_FUNCTION` options. However it is not obvious what type the payload of this callback is, as it is a pointer to an openssl object. We would probably need to parse that with the openssl R package, to do something meaningful with that.

Can you elaborate on your use case? Maybe it can be accomplished with any of the `curl::curl_options('ssl')` for example any of the [CURLOPT_SSL_OPTIONS](https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html) or [CURLOPT_SSL_VERIFYHOST](https://curl.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html)?

**Comment by jeroen** [comment]
If you can give an example of the sort of data you need about the TLS connection in your custom verify function, I can try to make a proof of concept.

**Comment by jeroen** [comment]
OK I have gotten something to work. However, this only works if R packages curl and openssl are dynamically linked to the same libssl, e.g. when using `libcurl4-openssl-dev` on Ubuntu.

It will likely crash when using statically linked curl and openssl due to ABI incompatibilities between libssl versions.

You can test it on MacOS but you have to make sure both curl and openssl are linked to homebrew openssl. This works:

```sh
# Make sure you have curl and openssl from homebrew
brew install curl openssl@1.1
```

In R we run:

```r
Sys.setenv(PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/curl/lib/pkgconfig")
remotes::install_github("jeroen/curl")
remotes::install_github("jeroen/openssl")
library(openssl)
example(ssl_ctx, run.dontrun = TRUE)
```

**Comment by jimhester** [comment]
Cool, I will give it a try, thank you for working on it 🙏

**Comment by jeroen** [comment]
This is on CRAN now.
